# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'jarvis_gui.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_jarvisUi(object):
    def setupUi(self, jarvisUi):
        jarvisUi.setObjectName("jarvisUi")
        jarvisUi.resize(1374, 731)
        self.centralwidget = QtWidgets.QWidget(jarvisUi)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(70, 40, 55, 16))
        self.label.setText("")
        self.label.setObjectName("label")
        self.bg_main = QtWidgets.QLabel(self.centralwidget)
        self.bg_main.setGeometry(QtCore.QRect(-20, -10, 1391, 691))
        self.bg_main.setText("")
        self.bg_main.setPixmap(QtGui.QPixmap("../../Downloads/movement-red-smoke-black-background-with-copy-space-writing-text.jpg"))
        self.bg_main.setScaledContents(True)
        self.bg_main.setObjectName("bg_main")
        self.bg_left = QtWidgets.QLabel(self.centralwidget)
        self.bg_left.setGeometry(QtCore.QRect(20, 20, 531, 291))
        self.bg_left.setStyleSheet("background-color :rgb(255, 90, 14)")
        self.bg_left.setText("")
        self.bg_left.setObjectName("bg_left")
        self.gif_left = QtWidgets.QLabel(self.centralwidget)
        self.gif_left.setGeometry(QtCore.QRect(30, 30, 511, 271))
        self.gif_left.setText("")
        self.gif_left.setPixmap(QtGui.QPixmap("../../Downloads/Q8i2.gif"))
        self.gif_left.setScaledContents(True)
        self.gif_left.setObjectName("gif_left")
        self.bg_right = QtWidgets.QLabel(self.centralwidget)
        self.bg_right.setGeometry(QtCore.QRect(990, 20, 371, 581))
        self.bg_right.setStyleSheet("background-color :rgb(255, 90, 14)")
        self.bg_right.setText("")
        self.bg_right.setObjectName("bg_right")
        self.gif_right = QtWidgets.QLabel(self.centralwidget)
        self.gif_right.setGeometry(QtCore.QRect(1000, 30, 351, 561))
        self.gif_right.setText("")
        self.gif_right.setPixmap(QtGui.QPixmap("../../Downloads/XjB8.gif"))
        self.gif_right.setScaledContents(True)
        self.gif_right.setObjectName("gif_right")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(570, 130, 381, 331))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("../../Downloads/VJl.gif"))
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(130, 470, 281, 51))
        self.pushButton.setStyleSheet("font: 10pt \"Ravie\";\n"
"background-color: rgb(255, 85, 0);\n"
"font: 10pt \"MS Shell Dlg 2\";\n"
"font: 16pt \"MS Shell Dlg 2\";\n"
"font: 8pt \"Tw Cen MT Condensed Extra Bold\";\n"
"font: 16pt \"Rockwell Condensed\";\n"
"font: 18pt \"MS Shell Dlg 2\";\n"
"font: 16pt \"Tw Cen MT Condensed Extra Bold\";\n"
"font: 20pt \"Tw Cen MT Condensed Extra Bold\";\n"
"text-color :rgb(255, 255, 255)")
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(130, 540, 281, 51))
        self.pushButton_2.setStyleSheet("font: 10pt \"Ravie\";\n"
"background-color: rgb(255, 85, 0);\n"
"font: 10pt \"MS Shell Dlg 2\";\n"
"font: 16pt \"MS Shell Dlg 2\";\n"
"font: 8pt \"Tw Cen MT Condensed Extra Bold\";\n"
"font: 16pt \"Rockwell Condensed\";\n"
"font: 18pt \"MS Shell Dlg 2\";\n"
"font: 16pt \"Tw Cen MT Condensed Extra Bold\";\n"
"font: 20pt \"Tw Cen MT Condensed Extra Bold\";\n"
"text-color :rgb(255, 255, 255)")
        self.pushButton_2.setObjectName("pushButton_2")
        jarvisUi.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(jarvisUi)
        self.statusbar.setObjectName("statusbar")
        jarvisUi.setStatusBar(self.statusbar)

        self.retranslateUi(jarvisUi)
        QtCore.QMetaObject.connectSlotsByName(jarvisUi)

    def retranslateUi(self, jarvisUi):
        _translate = QtCore.QCoreApplication.translate
        jarvisUi.setWindowTitle(_translate("jarvisUi", "MainWindow"))
        self.pushButton.setText(_translate("jarvisUi", "Start:---"))
        self.pushButton_2.setText(_translate("jarvisUi", "Stop:---"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    jarvisUi = QtWidgets.QMainWindow()
    ui = Ui_jarvisUi()
    ui.setupUi(jarvisUi)
    jarvisUi.show()
    sys.exit(app.exec_())
